name: Create GitHub Release

on:
  push:
    tags:
      - 'json-unit-parent-*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Extract version from tag
        id: extract_version
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/json-unit-parent-}
          echo "version=$TAG_NAME" >> $GITHUB_OUTPUT
          echo "Extracted version: $TAG_NAME"

      - name: Extract release notes
        id: extract_notes
        run: |
          VERSION="${{ steps.extract_version.outputs.version }}"
          
          # Extract the section for this version from RELEASES.md
          # The section starts with "## VERSION" and ends before the next "##" or end of file
          awk -v version="$VERSION" '
            BEGIN { found=0; printing=0 }
            /^## / {
              if (printing) exit
              if ($0 ~ "## " version) {
                found=1
                printing=1
                next
              }
            }
            printing { print }
            END { if (!found) exit 1 }
          ' RELEASES.md > release_notes.txt
          
          if [ $? -ne 0 ] || [ ! -s release_notes.txt ]; then
            echo "Could not find release notes for version $VERSION in RELEASES.md"
            exit 1
          fi
          
          echo "Release notes extracted successfully"
          cat release_notes.txt

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: release_notes.txt
          name: Version ${{ steps.extract_version.outputs.version }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
